---
# Create VRF

- hosts: controller
  remote_user: admin
  tasks:
    - name: Add a new VRF to a tenant
      aci_vrf:
        hostname: 10.188.28.4
        username: admin
        password: zse4XDR%
        vrf: vrf_lab
        tenant: Test_Dev
        descr: Lab VRF
        policy_control_preference: enforced
        policy_control_direction: ingress
        validate_certs: false
        protocol: https
        state: present
